/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as exchangeManageSol from "./ExchangeManage.sol";
export * as exchangeStakePoolSol from "./ExchangeStakePool.sol";
export * as exchangeStakePoolFactorySol from "./ExchangeStakePoolFactory.sol";
export * as makeOrderSol from "./MakeOrder.sol";
export * as walletSol from "./Wallet.sol";
