/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IExchangeStakePoolAbi,
  IExchangeStakePoolAbiInterface,
} from "../../ExchangeStakePool.sol/IExchangeStakePoolAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_exchangeManage",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExchangeStakePoolAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IExchangeStakePoolAbiInterface {
    return new utils.Interface(_abi) as IExchangeStakePoolAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExchangeStakePoolAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IExchangeStakePoolAbi;
  }
}
