/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExchangeManage__factory } from "./ExchangeManage__factory";
export { ExchangeManageAbi__factory } from "./ExchangeManageAbi__factory";
